GoProne (by Alpvax)
Just Enough Items (JEI) (by mezz)
Default Options (by BlayTheNinth)
Ceiling Torch (by bl4ckscor3)
Light Overlay (Rift/Forge/Fabric) (by shedaniel)
Tesseract (by SuperMartijn642)
Additional Enchanted Miner (by Kotori316)
RandomPatches (by TheRandomLabs)
Potions Master (by thevortexFoxTopia)
HunterIllager (by bagu_chan)
Storage Drawers (by Texelsaur)
AppleSkin (by squeek502)
Double Slabs (by CJMinecraft01)
GraveStone Mod (by henkelmax)
Cloth Config API (Forge) (by shedaniel)
Engineer's Tools (by wilechaote)
Rats (by alex1the1666)
Xaero's World Map (by xaero96)
Metal Barrels (by tfarecnim)
Vanilla Hammers [Forge] (by MelanX)
Dwarf Coal (by traverse_joe)
Double Doors (by Serilum)
Citadel (by alex1the1666)
End: Reborn (by elecatron)
Tubes Reloaded (by Commoble)
Crafting Tweaks (by BlayTheNinth)
Uppers (by vadis365)
Reload Audio Driver (RAD) [Forge] (by CJMinecraft01)
Traveller's Boots (by DenisMasterHerobrine)
MixinBootstrap (by LX_Gaming)
FancyMenu (by Keksuccino)
TrashSlot (by BlayTheNinth)
Patchouli (by Vazkii)
Custom Nausea (by TheIllusiveC4)
OpenBlocks Elevator (by vsngarcia)
GameMenuModOption (by morimori0317)
Bamboo Everything (Forge) (by Gaz_)
Large Fluid Tank (by Kotori316)
Scalable Cat's Force (by Kotori316)
Packing Tape (by gigaherz)
GravelMiner (by BlayTheNinth)
Client Tweaks (by BlayTheNinth)
Basic Nether Ores (by cScotPlay)
Variant16x (by BKthousand)
Look At That (by Tom_The_Geek)
CraftingCraft (by BlayTheNinth)
Bag of Yurting (by Commoble)
Cosmetic Armor Reworked (by LainMI)
Oh The Biomes You'll Go (by aocawol)
Collective (by Serilum)
Macaw's Bridges (by sketch_macaw)
Decorative Blocks (by stohun)
Backpacked (by MrCrayfish)
Cherished Worlds (by TheIllusiveC4)
QuantumStorage (by GigaBit101)
MoreVanillaLib (by MelanX)
Iron Chests (by ProgWML6)
Global XP (by bl4ckscor3)
Fast Leaf Decay (by olafskiii)
Iron Shulker Boxes (by ProgWML6)
Vanilla Excavators [Forge] (by MelanX)
Curios API (by TheIllusiveC4)
Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)
Mod Name Tooltip (by mezz)
Waddles (by Girafi)
Inventory Tweaks Renewed (by yuitakaa)
Mouse Tweaks (by YaLTeR)
Ding (by ohaiiChun)
Macaw's Doors (by sketch_macaw)
Xaero's Minimap (by xaero96)
Ma Essentials (by Maciej916)
Iron Furnaces (by XenoMustache)
